<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'REDIS_HASH' => 'Хеш',
    'REDIS_LIST' => 'Список',
    'REDIS_SET' => 'Набор',
    'REDIS_STRING' => 'Строка',
    'REDIS_UNDEFINED' => '---',
    'REDIS_ZSET' => 'Множество',
    'About' => 'О проекте',
    'Add' => 'Добавить',
    'Clearind Database' => 'Очистить базу',
    'Connect' => 'Подключить',
    'Connection' => 'Redis-подключение',
    'Connection Settings' => 'Настройки подключения',
    'Current Db num' => 'Текущая база',
    'Current Db storage' => 'Текущее подключение',
    'Database' => 'База',
    'Db Operations' => 'Операции с базой',
    'Enable query caching?' => 'Включить кеш запросов',
    'Encoding' => 'Redis-кодирование',
    'Expire' => 'Время до удаления ключа(TTL)',
    'Flush database' => 'Очистка базы',
    'Idle time' => 'Время с последнего изменения(Idletime)',
    'Info' => 'Информация о базе',
    'Key' => 'Redis-ключ',
    'Key Information' => 'Информация о ключе',
    'Key Length' => 'Размер',
    'Keys type' => 'Тип',
    'List Keys' => 'Ключи базы',
    'Logout' => 'Выход',
    'Main' => 'Главная',
    'Page Size' => 'На страницу',
    'Refcount' => 'Количество связанных ключей',
    'Save database' => 'Сохранить базу',
    'Search Key' => 'Поиск',
    'Search pattern' => 'Шаблон поиска',
    'Search query updated' => 'Поисковый запрос изменен',
    'Set Expire' => 'Установить время жизни (сек)',
    'Switched to' => 'Переключено на',
    'Type' => 'Тип',
    'Value' => 'Значение',
    'Wrong  redis type - it must be array' => 'Некорректное значение типа',
    'Wrong module configuration! Please set array of available redis connections' => 'Некорректная конфигурация модуля. Настройте доступные подключения к Редискам',
    'Wrong module configuration! Wrong configuration defRedis param' => 'Некорректная конфигурация модуля. Задайте правильное название соединения по умолчанию',
    'Wrong redis connection name' => 'Корявое название подключения к Редиске',
    'Wrong redis type' => 'Некорректное значение типа',
    'You really want to do it?' => 'Вы действительно намереваетесь свершить это деяние, не взирая на всю тяжесть и необратимость последствий? ',
    'database saving run in background' => 'Сохранение базы запущено в фоновом режиме',
    'hash' => 'Хеш',
    'key not found' => 'Ой, а ключика то нету такого:-( Бабайка утащил!',
    'list' => 'Список',
    'set' => 'Набор',
    'string' => 'Строка',
    'support redis patterns (*,?,[var])' => 'Поддерживаются шаблоны (*,?,[var])',
    'zset' => 'Множество',
    'Current Connection'=>'Текущее подключение',
    'Move To'=>'Переместить в...'
];
