<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Add' => '',
    'Clearind Database' => '',
    'Connect' => '',
    'Connection' => '',
    'Connection Settings' => '',
    'Current Db num' => '',
    'Current Db storage' => '',
    'Database' => '',
    'Db Operations' => '',
    'Enable query caching?' => '',
    'Encoding' => '',
    'Expire' => '',
    'Flush database' => '',
    'Idle time' => '',
    'Info' => '',
    'Key' => '',
    'Key Information' => '',
    'Key Length' => '',
    'Keys type' => '',
    'List' => '',
    'Logout' => '',
    'Main' => '',
    'Page Size' => '',
    'Refcount' => '',
    'Save database' => '',
    'Search Key' => '',
    'Search pattern' => '',
    'Search query updated' => '',
    'Set Expire' => '',
    'Switched to' => '',
    'Type' => '',
    'Value' => '',
    'Wrong  redis type - it must be array' => '',
    'Wrong module configuration! Please set array of available redis connections' => '',
    'Wrong module configuration! Wrong configuration defRedis param' => '',
    'Wrong redis connection name' => '',
    'Wrong redis type' => '',
    'You really want to do it?' => '',
    'database saving run in background' => '',
    'hash' => '',
    'key not found' => '',
    'list' => '',
    'set' => '',
    'string' => '',
    'support redis patterns (*,?,[var])' => '',
    'zset' => '',
];
